### ISSUE TITLE
Thread panic when trying to spawn agents on intersection

### ISSUE THREAD

**Issue by mdesantis** [dabreegster/abstreet#19] opened 2019-12-12 11:08 UTC
I've got the following thread panic trying to executing the first point of the "Playing the game" section of the readme:

> In sandbox mode, hover over an intersection, right click, and spawn agents. Then you can start the simulation by pressing space or clicking the icon.

```
HiDPI factor is purportedly 1
load map...
upload textures (14)... 0.0108s
14 textures grouped into 3 arrays (with the same dimensions)
Loading map ../data/system/maps/montlake.bin
Read ../data/system/maps/montlake.bin (4)... 0.0465s
create sim...
create sim took 0.0018s
Map and Sim cost ~10 MB
draw_map...
make DrawRoads (415)... 0.0271s
generate thick roads...
generate thick roads took 0.0028s
prepare DrawLanes (2,181)... 0.0358s
finalize DrawLanes (2,181)... 0.0353s
make DrawIntersections (317)... 0.0264s
generate unzoomed intersections...
generate unzoomed intersections took 0.0009s
make DrawBuildings (3,018)... 0.0074s
upload all buildings...
upload all buildings took 0.0041s
make DrawBusStop (16)... 0.0003s
make DrawAreas (55)... 0.0000s
upload all areas...
upload all areas took 0.0001s
create quadtree...
create quadtree took 0.0715s
static DrawMap consumes 9 MB on the GPU
draw_map... plus 0.0060s
draw_map took 0.2177s
DrawMap cost ~158 MB
load map... plus 0.0201s
load map took 0.2969s

- load map took 0.2969s
  - upload textures (14)... 0.0108s
  - Read ../data/system/maps/montlake.bin (4)... 0.0465s
  - create sim took 0.0018s
  - draw_map took 0.2177s
    - make DrawRoads (415)... 0.0271s
    - generate thick roads took 0.0028s
    - prepare DrawLanes (2,181)... 0.0358s
    - finalize DrawLanes (2,181)... 0.0353s
    - make DrawIntersections (317)... 0.0264s
    - generate unzoomed intersections took 0.0009s
    - make DrawBuildings (3,018)... 0.0074s
    - upload all buildings took 0.0041s
    - make DrawBusStop (16)... 0.0003s
    - make DrawAreas (55)... 0.0000s
    - upload all areas took 0.0001s
    - create quadtree took 0.0715s
    - ... plus 0.0060s
  - ... plus 0.0201s

5 notes:
14 textures grouped into 3 arrays (with the same dimensions)
Loading map ../data/system/maps/montlake.bin
Map and Sim cost ~10 MB
static DrawMap consumes 9 MB on the GPU
DrawMap cost ~158 MB

1 warnings:
Couldn't make geometry for TurnID(LaneID(531), LaneID(192), IntersectionID(52)). look for Pt2D(336.4989, 876.3308) to Pt2D(355.7037, 866.4475) in [Pt2D { inner_x: 336.3221, inner_y: 891.3298 }, Pt2D { inner_x: 336.4989, inner_y: 876.3308 }, Pt2D { inner_x: 345.5252, inner_y: 876.4371 }, Pt2D { inner_x: 355.3143, inner_y: 866.8297 }, Pt2D { inner_x: 366.594, inner_y: 876.7766 }, Pt2D { inner_x: 366.3413, inner_y: 891.7741 }, Pt2D { inner_x: 353.0851, inner_y: 891.5507 }, Pt2D { inner_x: 349.9952, inner_y: 897.5429 }, Pt2D { inner_x: 336.3221, inner_y: 891.3298 }]

- load map took 0.2969s
instantiate scenario...
instantiate scenario took 0.0000s

- instantiate scenario took 0.0000s

- instantiate scenario took 0.0000s
reset simulation...
reset simulation took 0.0046s

- reset simulation took 0.0046s

- reset simulation took 0.0046s
instantiate scenario...
instantiate scenario took 0.0000s

- instantiate scenario took 0.0000s

- instantiate scenario took 0.0000s
thread 'thread 'thread 'thread 'thread '<unnamed><unnamed>' panicked at '<unnamed>' panicked at 'no entry found for key' panicked at '', no entry found for keysrc/libcore/option.rs', :src/libcore/option.rs1190::<unnamed><unnamed>11905' panicked at ':
' panicked at 'no entry found for key5note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
', 
src/libcore/option.rs:no entry found for key', no entry found for key', thread 'src/libcore/option.rs1190<unnamed>thread '' panicked at ':<unnamed>no entry found for key1190:' panicked at '', :5no entry found for keysrc/libcore/option.rs
', :src/libcore/option.rssrc/libcore/option.rs:511901190
:thread ':<unnamed>5' panicked at ':
5no entry found for key1190
', :src/libcore/option.rs5:
1190:5
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x55cada4679f4 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x55cada4679f4 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x55cada4679f4 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x55cada4679f4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x55cada48f1bc - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x55cada4639f7 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x55cada469f15 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x55cada469f15 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55cada469f15 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x55cada469c06 - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x55cada46a615 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x55cada46a1b2 - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                               at src/libstd/panicking.rs:380
  12:     0x55cada46a0a6 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  13:     0x55cada48ae6a - core::panicking::panic_fmt::h527855ce0bc891f6
                               at src/libcore/panicking.rs:85
  14:     0x55cada48af67 - core::result::unwrap_failed::ha8b77e6004f0ba38
                               at src/libcore/result.rs:1165
  15:     0x55cada2f7c3c - scoped_threadpool::Scope::join_all::h90328822974430c3
  16:     0x55cad9ff3d44 - scoped_threadpool::Pool::scoped::h23d3c0a65b3839aa
  17:     0x55cad9f62db3 - abstutil::time::Timer::parallelize::ha823fecf13b2bbde
  18:     0x55cad9f4d13c - sim::make::spawner::TripSpawner::spawn_all::hc1532ecee05b9d68
  19:     0x55cad9f94edc - sim::sim::Sim::spawn_all_trips::he48301f395ddb241
  20:     0x55cad9dd1786 - game::sandbox::gameplay::spawner::spawn_agents_around::h313367c17e02f941
  21:     0x55cad9dcef57 - game::sandbox::gameplay::spawner::AgentSpawner::new::ha38fdaab740bd5cf
  22:     0x55cad9d774d3 - <game::sandbox::gameplay::freeform::Freeform as game::sandbox::gameplay::GameplayState>::event::h630c9b8defde470f
  23:     0x55cad9d781c0 - <game::sandbox::SandboxMode as game::game::State>::event::h15641abae535d20a
  24:     0x55cad9e0ea12 - <game::game::Game as ezgui::runner::GUI>::event::h9f61dcd2bd50e5d2
  25:     0x55cad9d36d11 - std::panicking::try::do_call::h2d6652771a795e52
  26:     0x55cada4727da - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  27:     0x55cad9df36c9 - ezgui::runner::State<G>::event::h89affbbdff6766dc
  28:     0x55cad9df506f - ezgui::runner::run::h7cacd4f4b053b02f
  29:     0x55cad9dd2bd6 - game::main::h5b516a8028736dc2
  30:     0x55cad9e3fbe3 - std::rt::lang_start::{{closure}}::h9e9cd991840640b1
  31:     0x55cada46a043 - std::rt::lang_start_internal::{{closure}}::ha04574f12d97cbe2
                               at src/libstd/rt.rs:49
  32:     0x55cada46a043 - std::panicking::try::do_call::h7c2a8488f72db90c
                               at src/libstd/panicking.rs:292
  33:     0x55cada4727da - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  34:     0x55cada46abcd - std::panicking::try::hc3a9b5da4250385d
                               at src/libstd/panicking.rs:271
  35:     0x55cada46abcd - std::panic::catch_unwind::hf27600bf8c37809a
                               at src/libstd/panic.rs:394
  36:     0x55cada46abcd - std::rt::lang_start_internal::h409d4f2fe51133b0
                               at src/libstd/rt.rs:48
  37:     0x55cad9dd2ca2 - main
  38:     0x7f2b46f8cb97 - __libc_start_main
  39:     0x55cad9c71afa - _start
  40:                0x0 - <unknown>
thread panicked while panicking. aborting.
fish: 'cargo run --release' terminated by signal SIGILL (Illegal instruction)
```

**Comment by b-camacho** [comment] 2019-12-12 13:45
+1, also got a crash while starting simulation
(Ubuntu 18.04 x86_64, i7-770HQ, GTX1050)
```
instantiate scenario...
Read ../data/system/scenarios/montlake/weekday_typical_traffic_from_psrc.bin (1)... 0.0160s
Instantiating weekday_typical_traffic_from_psrc...
load full neighborhood info...
load_all_objects from ../data/input/neighborhoods/montlake...
load_all_objects from ../data/input/neighborhoods/montlake took 0.0000s

- load_all_objects from ../data/input/neighborhoods/montlake took 0.0000s

- load_all_objects from ../data/input/neighborhoods/montlake took 0.0000s
load full neighborhood info took 0.0057s
seed individual parked cars (1,875)... 0.0044s
SpawnTrip (26,975)... 0.0051s
thread '<unnamed>' panicked at 'no entry found for key', src/libcore/option.rs:1034:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread '<unnamed>' panicked at 'no entry found for key', src/libcore/option.rs:1034:5
thread '<unnamed>thread '' panicked at '<unnamed>no entry found for key' panicked at '', no entry found for key', src/libcore/option.rssrc/libcore/option.rs::10341034:thread ':5<unnamed>
thread '5' panicked at '
<unnamed>no entry found for key' panicked at '', no entry found for keysrc/libcore/option.rs', :src/libcore/option.rs1034::10345:
5
thread '<unnamed>' panicked at 'no entry found for key', src/libcore/option.rs:1034:5
thread '<unnamed>' panicked at 'no entry found for key', src/libcore/option.rs:1034:5
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:999:5
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:999:5
stack backtrace:
   0:     0x564e3b832421 - std::sys_common::backtrace::print::h0158bc30f1f08e5f
   1:     0x564e3b83a262 - std::panicking::default_hook::{{closure}}::hd0e5ccf5a951fbfd
   2:     0x564e3b839ff3 - std::panicking::default_hook::ha72e5501b0ffb83c
   3:     0x564e3b83a950 - std::panicking::rust_panic_with_hook::hcca196f1f1162139
   4:     0x564e3b83a4e2 - std::panicking::continue_panic_fmt::hab503b114fbb56f8
   5:     0x564e3b83a3c6 - rust_begin_unwind
   6:     0x564e3b84fbdd - core::panicking::panic_fmt::haa3ad5d410001da3
   7:     0x564e3b6bd325 - core::result::unwrap_failed::hd77977b9fedbe029
   8:     0x564e3b6b6c4a - scoped_threadpool::Scope::join_all::hf48aa041f0a5a517
   9:     0x564e3b378d20 - scoped_threadpool::Pool::scoped::h1708f6e7698ef072
  10:     0x564e3b3ad453 - abstutil::time::Timer::parallelize::h37ac61b85717446f
  11:     0x564e3b3976a9 - sim::make::spawner::TripSpawner::spawn_all::h398387392e763dc9
  12:     0x564e3b2fc51d - sim::make::scenario::Scenario::instantiate::h2684c9bbbcfb5e44
  13:     0x564e3b12a21a - ezgui::event_ctx::EventCtx::loading_screen::h5a0b9e6801f790d4
  14:     0x564e3b163327 - game::sandbox::gameplay::GameplayRunner::initialize::h771063c3288f8090
  15:     0x564e3b0910a7 - game::sandbox::SandboxMode::new::hbd0f7fd9eba658ad
  16:     0x564e3b16361f - game::sandbox::gameplay::change_scenario::h0076a9bb8200f41f
  17:     0x564e3b05c7a2 - core::ops::function::Fn::call::h7dee61cb58e6bf06
  18:     0x564e3b139c05 - <game::game::WizardState as game::game::State>::event::h1b54ddabeb0a2f64
  19:     0x564e3b13805b - <game::game::Game as ezgui::runner::GUI>::event::h4c9b7d472ace1c00
  20:     0x564e3b05c611 - std::panicking::try::do_call::h2fcb73b958ded295
  21:     0x564e3b83e9ca - __rust_maybe_catch_panic
  22:     0x564e3b126bf8 - ezgui::runner::State<G>::event::hf50953513ffec574
  23:     0x564e3b128352 - ezgui::runner::run::hc8eab16c5dbee0ab
  24:     0x564e3b0eee96 - game::main::h085720c1f8e986ac
  25:     0x564e3b18c753 - std::rt::lang_start::{{closure}}::hc0f6c5f1358765f9
  26:     0x564e3b83a363 - std::panicking::try::do_call::hc3f3f274ffe6f0cd
  27:     0x564e3b83e9ca - __rust_maybe_catch_panic
  28:     0x564e3b829089 - std::rt::lang_start_internal::hb1dc547617272b6b
  29:     0x564e3b0eef62 - main
  30:     0x7fed33117b97 - __libc_start_main
  31:     0x564e3b00705a - _start
  32:                0x0 - <unknown>
thread panicked while panicking. aborting.
```
nonetheless, this project is amazing! looking forward to where it goes in the future

**Comment by dabreegster** [comment] 2019-12-12 17:52
Thanks for reporting! I'm having trouble reproducing either problem, but both are pathfinding breaking.

@mdesantis, from your logs, the spawn agents at intersection works a few times, but then breaks somewhere. Is that right? Can you tell me what IntersectionID you're hovering over when it breaks? (The bottom bar shows this. I'll add this to the logs to make it easier to debug in the future.)

@b-camacho, I'm very confused how this is happening. You're using a binary release? I'll add some better errors to figure this out.

**Comment by b-camacho** [comment] 2019-12-12 18:25
@dabreegster Thanks for looking into it!
I'm compiling from source, commit `77050761`. Could not run binary due to https://github.com/dabreegster/abstreet/issues/17, but I doubt these are related.

**Comment by dabreegster** [comment] 2019-12-12 18:42
@b-camacho, would you mind pulling and running again? You should see an error like ".... not in NodeMap". Somehow the contraction hierarchy built to speed up pathfinding isn't including one of the path endpoints.

**Comment by b-camacho** [comment] 2019-12-12 20:51
Sure enough, there it is
```
spawning agents around IntersectionID(108) (rng seed None)...
thread 'thread '<unnamed>' panicked at 'SidewalkEndpoint(LaneID(569), true) not in NodeMapthread '', <unnamed>map_model/src/pathfind/node_map.rs' panicked at ':SidewalkEndpoint(LaneID(1053), true) not in NodeMap36', :map_model/src/pathfind/node_map.rs13:
```
Exact repro steps are:
- run in either debug or release
- open sandbox
- click any intersection
- choose "spawn agents around this intersection"
Maybe it's relevant that instantiating scenarios causes the same panic.

Here's the full output:
```
HiDPI factor is purportedly 1.5
load map...
upload textures (14)... 0.3090s
14 textures grouped into 3 arrays (with the same dimensions)
Loading map ../data/system/maps/montlake.bin
Read ../data/system/maps/montlake.bin (4)... 0.4513s
create sim...
create sim took 0.0293s
Map and Sim cost ~10 MB
draw_map...
make DrawRoads (415)... 0.2329s
generate thick roads...
generate thick roads took 0.0215s
prepare DrawLanes (2,181)... 0.1751s
finalize DrawLanes (2,181)... 0.1344s
make DrawIntersections (317)... 0.1905s
generate unzoomed intersections...
generate unzoomed intersections took 0.0082s
make DrawBuildings (3,018)... 0.0691s
upload all buildings...
upload all buildings took 0.0124s
make DrawBusStop (16)... 0.0015s
make DrawAreas (55)... 0.0002s
upload all areas...
upload all areas took 0.0003s
create quadtree...
create quadtree took 0.3998s
static DrawMap consumes 9 MB on the GPU
draw_map... plus 0.0579s
draw_map took 1.3037s
DrawMap cost ~560 MB
load map... plus 0.0558s
load map took 2.1491s

- load map took 2.1491s
  - upload textures (14)... 0.3090s
  - Read ../data/system/maps/montlake.bin (4)... 0.4513s
  - create sim took 0.0293s
  - draw_map took 1.3037s
    - make DrawRoads (415)... 0.2329s
    - generate thick roads took 0.0215s
    - prepare DrawLanes (2,181)... 0.1751s
    - finalize DrawLanes (2,181)... 0.1344s
    - make DrawIntersections (317)... 0.1905s
    - generate unzoomed intersections took 0.0082s
    - make DrawBuildings (3,018)... 0.0691s
    - upload all buildings took 0.0124s
    - make DrawBusStop (16)... 0.0015s
    - make DrawAreas (55)... 0.0002s
    - upload all areas took 0.0003s
    - create quadtree took 0.3998s
    - ... plus 0.0579s
  - ... plus 0.0558s

5 notes:
14 textures grouped into 3 arrays (with the same dimensions)
Loading map ../data/system/maps/montlake.bin
Map and Sim cost ~10 MB
static DrawMap consumes 9 MB on the GPU
DrawMap cost ~560 MB

1 warnings:
Couldn't make geometry for TurnID(LaneID(531), LaneID(192), IntersectionID(52)). look for Pt2D(336.4989, 876.3308) to Pt2D(355.7037, 866.4475) in [Pt2D { inner_x: 336.3221, inner_y: 891.3298 }, Pt2D { inner_x: 336.4989, inner_y: 876.3308 }, Pt2D { inner_x: 345.5252, inner_y: 876.4371 }, Pt2D { inner_x: 355.3143, inner_y: 866.8297 }, Pt2D { inner_x: 366.594, inner_y: 876.7766 }, Pt2D { inner_x: 366.3413, inner_y: 891.7741 }, Pt2D { inner_x: 353.0851, inner_y: 891.5507 }, Pt2D { inner_x: 349.9952, inner_y: 897.5429 }, Pt2D { inner_x: 336.3221, inner_y: 891.3298 }]

- load map took 2.1491s
instantiate scenario...
instantiate scenario took 0.0000s

- instantiate scenario took 0.0000s

- instantiate scenario took 0.0000s
spawning agents around IntersectionID(108) (rng seed None)...
thread 'thread '<unnamed>' panicked at 'SidewalkEndpoint(LaneID(569), true) not in NodeMapthread '', <unnamed>map_model/src/pathfind/node_map.rs' panicked at ':SidewalkEndpoint(LaneID(1053), true) not in NodeMap36', :map_model/src/pathfind/node_map.rs13:
36note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread ':<unnamed>13' panicked at '
SidewalkEndpoint(LaneID(691), true) not in NodeMap', map_model/src/pathfind/node_map.rs:36:13
<unnamed>' panicked at 'SidewalkEndpoint(LaneID(998), true) not in NodeMap', map_model/src/pathfind/node_map.rs:36:13
thread '<unnamed>' panicked at 'SidewalkEndpoint(LaneID(1944), false) not in NodeMap', map_model/src/pathfind/node_map.rs:36:13
thread '<unnamed>' panicked at 'SidewalkEndpoint(LaneID(642), false) not in NodeMap', map_model/src/pathfind/node_map.rs:36:13
thread '<unnamed>' panicked at 'SidewalkEndpoint(LaneID(483), false) not in NodeMap', map_model/src/pathfind/node_map.rs:36:13
thread '<unnamed>' panicked at 'SidewalkEndpoint(LaneID(1340), true) not in NodeMap', map_model/src/pathfind/node_map.rs:36:13
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:999:5
stack backtrace:
   0:     0x5584287b2a61 - std::sys_common::backtrace::print::h0158bc30f1f08e5f
   1:     0x5584287ba8a2 - std::panicking::default_hook::{{closure}}::hd0e5ccf5a951fbfd
   2:     0x5584287ba633 - std::panicking::default_hook::ha72e5501b0ffb83c
   3:     0x5584287baf90 - std::panicking::rust_panic_with_hook::hcca196f1f1162139
   4:     0x5584287bab22 - std::panicking::continue_panic_fmt::hab503b114fbb56f8
   5:     0x5584287baa06 - rust_begin_unwind
   6:     0x5584287d023d - core::panicking::panic_fmt::haa3ad5d410001da3
   7:     0x5584281bfdca - core::result::unwrap_failed::hafd032a06f103130
                               at /usr/src/rustc-1.37.0/src/libcore/macros.rs:18
   8:     0x5584281c0e95 - core::result::Result<T,E>::unwrap::hbe4130a0022f30a4
                               at /usr/src/rustc-1.37.0/src/libcore/result.rs:800
   9:     0x5584281c4476 - scoped_threadpool::Scope::join_all::hd88dc208fba1b3ce
                               at /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:219
  10:     0x5584281c467f - <scoped_threadpool::Scope as core::ops::drop::Drop>::drop::h85194363c5c1baad
                               at /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:248
  11:     0x558426ad014f - core::ptr::real_drop_in_place::h398d5ef157afc50a
                               at /usr/src/rustc-1.37.0/src/libcore/ptr/mod.rs:197
  12:     0x558427191955 - scoped_threadpool::Pool::scoped::h84636df52e3e0468
                               at /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:182
  13:     0x558426c7b620 - abstutil::time::Timer::parallelize::he7a21c2c5926e1bd
                               at /home/brian/tools/abstreet/abstutil/src/time.rs:325
  14:     0x558426d6a462 - sim::make::spawner::TripSpawner::spawn_all::h212ce524fca724a9
                               at sim/src/make/spawner.rs:191
  15:     0x558426bdb44c - sim::sim::Sim::spawn_all_trips::h5badbb5b96a7b1f3
                               at sim/src/sim.rs:162
  16:     0x55842649b187 - game::sandbox::gameplay::spawner::spawn_agents_around::h55a5844f510fea29
                               at game/src/sandbox/gameplay/spawner.rs:356
  17:     0x5584264996c9 - game::sandbox::gameplay::spawner::AgentSpawner::new::h3b0c505bd74d3ac5
                               at game/src/sandbox/gameplay/spawner.rs:160
  18:     0x5584266729b4 - <game::sandbox::gameplay::freeform::Freeform as game::sandbox::gameplay::GameplayState>::event::h0e25d9bb8c5ebaab
                               at game/src/sandbox/gameplay/freeform.rs:57
  19:     0x5584267e3852 - game::sandbox::gameplay::GameplayRunner::event::h0c2acd4d1ad04e75
                               at game/src/sandbox/gameplay/mod.rs:197
  20:     0x5584264c536b - <game::sandbox::SandboxMode as game::game::State>::event::hc0038cc46a87faf6
                               at game/src/sandbox/mod.rs:95
  21:     0x5584267c36fd - <game::game::Game as ezgui::runner::GUI>::event::he1bf1746280ac84f
                               at game/src/game.rs:44
  22:     0x5584264c1ede - ezgui::runner::State<G>::event::{{closure}}::h03c5b195d8a0f687
                               at /home/brian/tools/abstreet/ezgui/src/runner.rs:84
  23:     0x5584264320b1 - core::ops::function::FnOnce::call_once::hda0cbd78de9397d9
                               at /usr/src/rustc-1.37.0/src/libcore/ops/function.rs:231
  24:     0x55842667d678 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha172cc84c455c50b
                               at /usr/src/rustc-1.37.0/src/libstd/panic.rs:315
  25:     0x558426353e2b - std::panicking::try::do_call::heedc7547f4b21649
                               at /usr/src/rustc-1.37.0/src/libstd/panicking.rs:296
  26:     0x5584287bf00a - __rust_maybe_catch_panic
  27:     0x558426353a39 - std::panicking::try::h1acac747bee48db4
                               at /usr/src/rustc-1.37.0/src/libstd/panicking.rs:275
  28:     0x55842667d6f8 - std::panic::catch_unwind::h42b065837ab66a6d
                               at /usr/src/rustc-1.37.0/src/libstd/panic.rs:394
  29:     0x5584264c16ed - ezgui::runner::State<G>::event::h48a2232029bcf607
                               at /home/brian/tools/abstreet/ezgui/src/runner.rs:83
  30:     0x5584264c033b - ezgui::runner::loop_forever::hc8ef5978c7e57a29
                               at /home/brian/tools/abstreet/ezgui/src/runner.rs:402
  31:     0x5584264c2a9e - ezgui::runner::run::hb6bb507e4722275c
                               at /home/brian/tools/abstreet/ezgui/src/runner.rs:302
  32:     0x558426571766 - game::main::hfae87231e2072153
                               at game/src/main.rs:51
  33:     0x55842665d900 - std::rt::lang_start::{{closure}}::h138df2120edec7d1
                               at /usr/src/rustc-1.37.0/src/libstd/rt.rs:64
  34:     0x5584287ba9a3 - std::panicking::try::do_call::hc3f3f274ffe6f0cd
  35:     0x5584287bf00a - __rust_maybe_catch_panic
  36:     0x5584287a96c9 - std::rt::lang_start_internal::hb1dc547617272b6b
  37:     0x55842665d8d9 - std::rt::lang_start::h4d1b110bcc73c83e
                               at /usr/src/rustc-1.37.0/src/libstd/rt.rs:64
  38:     0x55842657191a - main
  39:     0x7f42b8aa5b97 - __libc_start_main
  40:     0x55842635172a - _start
  41:                0x0 - <unknown>
thread panicked while panicking. aborting.
[1]    6395 illegal hardware instruction (core dumped)  cargo run
```

**Comment by dabreegster** [comment] 2019-12-12 22:23
Ah, those nodes are from e4a34306b0dd956d96f08a32e99210afec45d50c. Since you're running from source, I think when you ran data/grab_seed_data.sh, you got an old set of maps. I updated the data there about an hour ago. If you grab_seed_data.sh and run again, everything should be fine.

Prevention in the future: I need to make sure to upload new seed data as soon as something changes. I'll look into changing the map building pipeline to put checksums of files under version control, so it's very obvious when I need to upload again.

**Comment by dabreegster** [comment] 2019-12-13 17:35
#25 and #26 were the same issue and were fixed by grabbing the new map data, so closing this bug too. I'll make sure to keep the data updated for people building from source. Let me know if you hit any other problems!  (Still looking into the Linux binary compatibility problem)

**Closed by dabreegster** 2019-12-13 17:35 UTC
