### ISSUE TITLE
Support more fonts for cities with non-Latin glyphs in names

### ISSUE THREAD

**Issue by jjdblast** [dabreegster/abstreet#226] opened 2020-07-22 16:10 UTC
Getting a crash when using a new map in sandbox mode.

I try to import part of shanghai osm data (Yangpu District) into abstreet.

- Mac: 10.15.6
- abstreet: https://github.com/dabreegster/abstreet/commit/38b8557c82dfa25b818af97db3430b1b9cb7ec5a

My steps: 

1. Put [yangpu.osm](https://drive.google.com/file/d/1hCgMtUdSvJOtKr_R30L9ZHoRosqGq2Y_/view?usp=sharing) in `data/input/shanghai/osm`, also put [yangpu.poly](https://drive.google.com/file/d/15z5phaQi9ukEaEiDUxFIXWpn8Wgb_BcG/view?usp=sharing) in `data/input/shanghai/polygons`
2. Modify importer and updater just like step 4-8 in this guide: https://github.com/dabreegster/abstreet/blob/master/docs/new_city.md#including-the-city-by-default
3. Running the game: `RUST_BACKTRACE=1 cargo run --bin game --release`
4. My click sequence: "Play" - "SANDBOX" - "Map" on the top - Choose yangpu in "Other Cities" - Crash in "make DrawIntersections"

> - switch map took 1.7934s
> switch map...
> Wrote data/player/camera_state/huge_krakow.json
> load map...
> Loading map data/system/maps/yangpu.bin
> Read data/system/maps/yangpu.bin (25)... 0.4821s
> create sim...
> create sim took 0.0132s
> Map and Sim cost ~0 MB
> draw_map...
> make DrawRoads (2,072)... 0.1740s
> make DrawLanes (10,084)... 0.0424s
> make DrawIntersections (1,426)... 0.1990s
> generate unzoomed roads and intersections...
> thread 'main' panicked at 'Unknown OSM highway platform', map_model/src/objects/road.rs:368:22
> stack backtrace:
>    0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
>    1: core::fmt::write
>    2: std::io::Write::write_fmt
>    3: std::panicking::default_hook::{{closure}}
>    4: std::panicking::default_hook
>    5: std::panicking::rust_panic_with_hook
>    6: rust_begin_unwind
>    7: std::panicking::begin_panic_fmt
>    8: map_model::objects::road::Road::get_rank
>    9: game::render::map::DrawMap::regenerate_unzoomed_layer
>   10: game::render::map::DrawMap::new
>   11: game::app::App::new
>   12: game::app::App::switch_map
>   13: ezgui::event_ctx::EventCtx::loading_screen
>   14: <game::common::city_picker::CityPicker as game::game::State>::event
>   15: <game::game::Game as ezgui::runner::GUI>::event
>   16: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
>   17: ezgui::runner::State<G>::event
>   18: ezgui::runner::run::{{closure}}
>   19: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
>   20: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
>   21: winit::platform_impl::platform::app_state::AppState::cleared
>   22: _ZL12preoptimized
>   23: _ZL12preoptimized
>   24: _ZL12preoptimized
>   25: _ZL12preoptimized
>   26: _ZL12preoptimized
>   27: _ZL12preoptimized
>   28: _ZL12preoptimized
>   29: _ZL12preoptimized
>   30: _ZL12preoptimized
>   31: _ZL12preoptimized
>   32: winit::platform_impl::platform::event_loop::EventLoop<T>::run
>   33: winit::event_loop::EventLoop<T>::run
>   34: ezgui::runner::run
>   35: game::main
>   36: std::rt::lang_start::{{closure}}
>   37: std::rt::lang_start_internal
>   38: main
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> dropping Timer during generate unzoomed roads and intersections, due to panic?
> switch map took 1.6991s
> 
> - switch map took 1.6991s
> 
> - switch map took 1.6991s
> 
> ********************************************************************************
> Wrote data/player/camera_state/huge_krakow.json
> Crash! Please report to https://github.com/dabreegster/abstreet/issues/ and include all output.txt; at least everything starting from the stack trace above!
> 
> At 00:00:02.6
> 
> Camera:
> { "cam_x": 44093.703687090216, "cam_y": 43012.39372756959, "cam_zoom": 22.51371661936363 }
> 
> No edits
> 
> Crash! Please report to https://github.com/dabreegster/abstreet/issues/ and include all output.txt; at least everything above here until the start of the report!
> ********************************************************************************

**Comment by dabreegster** [comment] 2020-07-22 16:14
Thanks for reporting the bug! The problem is `Unknown OSM highway platform`. Those should only be interpreted for matching transit stops, but it looks like somehow one of them wound up being marked as a road.

Since you're building from source, the quick workaround is to edit `map_model/src/objects/road.rs`, look for `get_rank`, and add `"platform" => 0` near the bottom.

I'll import the .osm file later today and look into the issue more closely.

**Comment by jjdblast** [comment] 2020-07-22 17:04
I add `"platform" => 0` in road.rs, now problem is solved and everything looks fine, thanks !

Maybe I can add more districts or cities, before that I need to learn some best practices to send PR :)

**Comment by dabreegster** [comment] 2020-07-22 17:09
Great! Let me know if you have any other questions. There aren't really many contribution guidelines; if you can, run `cargo +nightly fmt` to automatically style the code before a PR.

**Comment by dabreegster** [comment] 2020-07-22 21:20
The import bug is fixed; you don't need the changes to `objects/road`.

I'm seeing pretty much all of the names missing, because https://fonts.google.com/specimen/Overpass doesn't include Chinese glyphs. Any recommendation for a font to use instead?

**Comment by jjdblast** [comment] 2020-07-23 04:58
For Simplified Chinese, Noto Sans SC is a good choice, which also supports Japanese character. https://fonts.google.com/specimen/Noto+Sans+SC

Another choice is Source Han Sans, which is free for commercial use https://github.com/adobe-fonts/source-han-sans/

**Comment by dabreegster** [comment] 2020-07-29 15:40
Sorry for the delayed response. Both Noto and Source Han Sans are OTF fonts. I couldn't get `fontdb` to load them; I think it only handles TTF. I found https://fonts.google.com/specimen/ZCOOL+XiaoWei?subset=chinese-simplified#glyphs as one option. I made a [branch](https://github.com/dabreegster/abstreet/tree/font_zcool_xiao_wei) that loads it.

- I was worried how to toggle between Overpass and Xiao Wei as the default font, but actually, it looks like some combination of `usvg` and `fontdb` already handle font fallback. There may be some small bugs with drawing outlines behind text, because of caching hints that key off of the explicitly specified font, but I haven't noticed any.
- The other TTF fonts included so far are 200KB, but Xiao Wei is 6MB. That's not bad to include in the git repository, but I'm not sure this approach will scale if more cities need more large fonts. Including in the release is fine, but making the initial `git clone` sluggish might not be. I'll see about shipping larger font files through the `updater` tool instead.

**Closed** 2020-08-18 03:34 UTC
Labels: map quality
