### ISSUE TITLE
Startup crash on Windows 10 dev environment.

### ISSUE THREAD

**Issue by alimon808** [dabreegster/abstreet#43] opened 2020-02-05 19:33 UTC
![abstreet-int-overflow-exception](https://user-images.githubusercontent.com/858582/73875927-e958b880-480a-11ea-817f-ccb0767e26ff.PNG)

**Comment by dabreegster** [comment] 2020-02-05 19:39
The code and data are out of sync. git pull, and run ./data/grab_seed_data.sh again (or rebuild the maps yourself). I'll add some error handling here to explain what's happening more clearly

**Comment by alimon808** [comment] 2020-02-05 20:24
I'm getting the same error.  Grab the latest data and performed a git pull on the current local repo.  No luck.  Tried also a completely new clone and performed the same steps but still no luck.  Maybe it's a windows thing, I'll try on mac later today.

**Comment by alimon808** [comment] 2020-02-06 03:34
It works fine on mac.  I was able to compile and run the game.  

On Windows, I tried also using the Windows Subsystem for Linux(WSL) feature with Ubuntu.  Compiling and running the game within Ubuntu using this feature, the game still crashed at startup with the following error:

![abstreet-ubuntu-startup-error](https://user-images.githubusercontent.com/858582/73903535-3b6efd80-484e-11ea-80f1-1cadb7008bcf.PNG)

**Comment by dabreegster** [comment] 2020-02-06 19:20
The WSL issue seems like an issue with https://github.com/rust-windowing/winit. Since you compiled on Ubuntu, winit found bindings to wayland (your display server), but when you run on Windows, wayland doesn't exist.

The very first error is a serde deserialization error. Every time I've seen it, it means the file I'm reading was serialized with older code. I've never seen a difference between platforms matter.

What I'll work on:
- better errors when running the game if map data is missing or out-of-date
- a script to download a much smaller set of files to run from source (you won't be able to rebuild maps from scratch, but you'll be able to work on the simulation and GUI layers)
- figuring out what the deserialization issue is here

**Comment by dabreegster** [comment] 2020-02-07 23:15
First two problems fixed. I don't have a Windows env and so can't easily help debug. Seems like using WSL doesn't work (kind of by design), so if you try again normally and still get the "invalid value" deserialization error, check the md5sum of the montlake.bin file. It should match data/MANIFEST.txt's entry.

**Comment by dabreegster** [comment] 2020-05-03 02:29
Closing old bugs. If you're still having issues, please reopen. Thanks!

**Closed by dabreegster** 2020-05-03 02:29 UTC
