### ISSUE TITLE
Failed to download stuff: ["data/input/raw_maps/lakeslice.bin"]', updater/src/main.rs:69:9

### ISSUE THREAD

**Issue by yurivict** [dabreegster/abstreet#213] opened 2020-07-20 16:03 UTC
```
> download https://www.dropbox.com/s/5rgtxl9xglnyxrz/weekday.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/scenarios/west_seattle/weekday.bin
>   file 0 extracted to "data/system/scenarios/west_seattle/weekday.bin"
> rm tmp_download.zip
thread 'main' panicked at 'Failed to download stuff: ["data/input/raw_maps/lakeslice.bin"]', updater/src/main.rs:69:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: updater::download::{{closure}}
             at updater/src/main.rs:69
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libcore/future/mod.rs:66
  10: updater::main::{{closure}}
             at updater/src/main.rs:30
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libcore/future/mod.rs:66
  12: tokio::runtime::enter::Enter::block_on::{{closure}}
             at ./cargo-crates/tokio-0.2.21/src/runtime/enter.rs:163
  13: tokio::coop::with_budget::{{closure}}
             at ./cargo-crates/tokio-0.2.21/src/coop.rs:127
  14: std::thread::local::LocalKey<T>::try_with
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libstd/thread/local.rs:263
  15: std::thread::local::LocalKey<T>::with
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libstd/thread/local.rs:239
  16: tokio::coop::with_budget
             at ./cargo-crates/tokio-0.2.21/src/coop.rs:120
  17: tokio::coop::budget
             at ./cargo-crates/tokio-0.2.21/src/coop.rs:96
  18: tokio::runtime::enter::Enter::block_on
             at ./cargo-crates/tokio-0.2.21/src/runtime/enter.rs:163
  19: tokio::runtime::thread_pool::ThreadPool::block_on
             at ./cargo-crates/tokio-0.2.21/src/runtime/thread_pool/mod.rs:82
  20: tokio::runtime::Runtime::block_on::{{closure}}
             at ./cargo-crates/tokio-0.2.21/src/runtime/mod.rs:446
  21: tokio::runtime::context::enter
             at ./cargo-crates/tokio-0.2.21/src/runtime/context.rs:72
  22: tokio::runtime::handle::Handle::enter
             at ./cargo-crates/tokio-0.2.21/src/runtime/handle.rs:76
  23: tokio::runtime::Runtime::block_on
             at ./cargo-crates/tokio-0.2.21/src/runtime/mod.rs:441
  24: updater::main
             at updater/src/main.rs:11
  25: std::rt::lang_start::{{closure}}
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libstd/rt.rs:67
  26: std::rt::lang_start_internal
  27: std::rt::lang_start
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libstd/rt.rs:67
  28: main
  29: _start
             at /usr/src/lib/csu/amd64/crt1.c:76
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by dabreegster** [comment] 2020-07-20 16:16
I just checked all the Dropbox links; they should be good. This was a flake. Some ideas for improvement:

- Include the error message in the final summary, so it's clear it was some transient DNS issue, for example
- add some simple retry logic to the http client

**Comment by yurivict** [comment] 2020-07-20 16:42
It is reproducible:
```
> download https://www.dropbox.com/s/5rgtxl9xglnyxrz/weekday.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/scenarios/west_seattle/weekday.bin
>   file 0 extracted to "data/system/scenarios/west_seattle/weekday.bin"
> rm tmp_download.zip
thread 'main' panicked at 'Failed to download stuff: ["data/input/raw_maps/lakeslice.bin"]', updater/src/main.rs:69:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: updater::download::{{closure}}
             at updater/src/main.rs:69
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libcore/future/mod.rs:66
  10: updater::main::{{closure}}
             at updater/src/main.rs:30
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libcore/future/mod.rs:66
  12: tokio::runtime::enter::Enter::block_on::{{closure}}
             at ./cargo-crates/tokio-0.2.21/src/runtime/enter.rs:163
  13: tokio::coop::with_budget::{{closure}}
             at ./cargo-crates/tokio-0.2.21/src/coop.rs:127
  14: std::thread::local::LocalKey<T>::try_with
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libstd/thread/local.rs:263
  15: std::thread::local::LocalKey<T>::with
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libstd/thread/local.rs:239
  16: tokio::coop::with_budget
             at ./cargo-crates/tokio-0.2.21/src/coop.rs:120
  17: tokio::coop::budget
             at ./cargo-crates/tokio-0.2.21/src/coop.rs:96
  18: tokio::runtime::enter::Enter::block_on
             at ./cargo-crates/tokio-0.2.21/src/runtime/enter.rs:163
  19: tokio::runtime::thread_pool::ThreadPool::block_on
             at ./cargo-crates/tokio-0.2.21/src/runtime/thread_pool/mod.rs:82
  20: tokio::runtime::Runtime::block_on::{{closure}}
             at ./cargo-crates/tokio-0.2.21/src/runtime/mod.rs:446
  21: tokio::runtime::context::enter
             at ./cargo-crates/tokio-0.2.21/src/runtime/context.rs:72
  22: tokio::runtime::handle::Handle::enter
             at ./cargo-crates/tokio-0.2.21/src/runtime/handle.rs:76
  23: tokio::runtime::Runtime::block_on
             at ./cargo-crates/tokio-0.2.21/src/runtime/mod.rs:441
  24: updater::main
             at updater/src/main.rs:11
  25: std::rt::lang_start::{{closure}}
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libstd/rt.rs:67
  26: std::rt::lang_start_internal
  27: std::rt::lang_start
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libstd/rt.rs:67
  28: main
  29: _start
             at /usr/src/lib/csu/amd64/crt1.c:76
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by dabreegster** [comment] 2020-07-20 16:50
The real error message is earlier; you could search backwards for `data/input/raw_maps/lakeslice.bin`. Or if you sync and retry, the full error will be printed at the end. But I suspect the issue is that you had an old copy of `data/MANIFEST`, and syncing should fix.

(I still haven't sorted out a way to host a copy of `data/` for the last few releases. The mapping between filename and specific URLs in Dropbox is hard to work with. I might move to an S3 bucket or something similar, where you can build the URL just by knowing the filename. I wish Dropbox had something like that, just a normal "host this public folder" option.)

**Comment by yurivict** [comment] 2020-07-20 17:02
I just took the 0.2.4 version.

**Comment by dabreegster** [comment] 2020-07-20 17:07
Ah, then this is expected failure right now. This is a duplicate of #195. I'll try and find a resolution for that this week, but it's been a little busy. I'm hoping to wind up with something closer to:

`http://s3.amazonaws.com/abstreet_data/latest/data/system/maps...`

and

`http://s3.amazonaws.com/abstreet_data/0.2.4/data/system/maps...`

But I have to change my release process to deal with that, and probably add some flags to the updater to pin to a release. Or auto-detect the release by looking at the label on the current git commit.

**Comment by yurivict** [comment] 2020-07-20 18:46
No luck with the latest revision 0.2.4-9-g10f8ddde

```
> download https://www.dropbox.com/s/bcean6p6fftj4ep/lakeslice.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/bcean6p6fftj4ep/lakeslice.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/bcean6p6fftj4ep/lakeslice.bin.zip), but continuing
> rm tmp_download.zip
> download https://www.dropbox.com/s/tfra95r79dpmz0n/montlake.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/raw_maps/montlake.bin
>   file 0 extracted to "data/input/raw_maps/montlake.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/8w6gdsql5sashbt/south_seattle.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/raw_maps/south_seattle.bin
>   file 0 extracted to "data/input/raw_maps/south_seattle.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/db4nhgmk0ggwai8/udistrict.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/raw_maps/udistrict.bin
>   file 0 extracted to "data/input/raw_maps/udistrict.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/87ijfmz1nntem8i/west_seattle.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/raw_maps/west_seattle.bin
>   file 0 extracted to "data/input/raw_maps/west_seattle.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/qawd35wz62m2acl/downtown.zip.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/screenshots/downtown.zip
>   file 0 extracted to "data/input/screenshots/downtown.zip"
> rm tmp_download.zip
> download https://www.dropbox.com/s/dbzon7k5ukndtza/huge_krakow.zip.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/screenshots/huge_krakow.zip
>   file 0 extracted to "data/input/screenshots/huge_krakow.zip"
> rm tmp_download.zip
> download https://www.dropbox.com/s/z0z96lsn7bunqfy/lakeslice.zip.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/screenshots/lakeslice.zip
>   file 0 extracted to "data/input/screenshots/lakeslice.zip"
> rm tmp_download.zip
> download https://www.dropbox.com/s/r9vkgwesqklfuq2/montlake.zip.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/screenshots/montlake.zip
>   file 0 extracted to "data/input/screenshots/montlake.zip"
> rm tmp_download.zip
> download https://www.dropbox.com/s/ecnt1tyza48y9o2/udistrict.zip.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/screenshots/udistrict.zip
>   file 0 extracted to "data/input/screenshots/udistrict.zip"
> rm tmp_download.zip
> download https://www.dropbox.com/s/mmb4mgutwotijdw/N47W122.hgt.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/N47W122.hgt
>   file 0 extracted to "data/input/seattle/N47W122.hgt"
> rm tmp_download.zip
> download https://www.dropbox.com/s/rxd2care60tbe75/blockface.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/blockface.bin
>   file 0 extracted to "data/input/seattle/blockface.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/ukknmpjdvilncq9/blockface.kml.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/blockface.kml
>   file 0 extracted to "data/input/seattle/blockface.kml"
> rm tmp_download.zip
> download https://www.dropbox.com/s/7j2gwb18685kd5u/offstreet_parking.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/offstreet_parking.bin
>   file 0 extracted to "data/input/seattle/offstreet_parking.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/dkkkpywob7cdo57/offstreet_parking.kml.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/offstreet_parking.kml
>   file 0 extracted to "data/input/seattle/offstreet_parking.kml"
> rm tmp_download.zip
> download https://www.dropbox.com/s/dy0yvynlk9ocf2r/ballard.osm.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/osm/ballard.osm
>   file 0 extracted to "data/input/seattle/osm/ballard.osm"
> rm tmp_download.zip
> download https://www.dropbox.com/s/babtm8mqoifmvta/downtown.osm.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/osm/downtown.osm
>   file 0 extracted to "data/input/seattle/osm/downtown.osm"
> rm tmp_download.zip
> download https://www.dropbox.com/s/t99sqz78zx48tx3/huge_seattle.osm.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/osm/huge_seattle.osm
>   file 0 extracted to "data/input/seattle/osm/huge_seattle.osm"
> rm tmp_download.zip
> download https://www.dropbox.com/s/xwxdvhnw5pgyove/lakeslice.osm.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/osm/lakeslice.osm
>   file 0 extracted to "data/input/seattle/osm/lakeslice.osm"
> rm tmp_download.zip
> download https://www.dropbox.com/s/jfi5px73x0txeom/montlake.osm.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/osm/montlake.osm
>   file 0 extracted to "data/input/seattle/osm/montlake.osm"
> rm tmp_download.zip
> download https://www.dropbox.com/s/8baooombjfz8mbv/south_seattle.osm.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/osm/south_seattle.osm
>   file 0 extracted to "data/input/seattle/osm/south_seattle.osm"
> rm tmp_download.zip
> download https://www.dropbox.com/s/s3yb9xqbjuntu3v/udistrict.osm.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/osm/udistrict.osm
>   file 0 extracted to "data/input/seattle/osm/udistrict.osm"
> rm tmp_download.zip
> download https://www.dropbox.com/s/a6dax5p59ltjetm/washington-latest.osm.pbf.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/osm/washington-latest.osm.pbf
>   file 0 extracted to "data/input/seattle/osm/washington-latest.osm.pbf"
> rm tmp_download.zip
> download https://www.dropbox.com/s/gsvwkd854wvyz5d/west_seattle.osm.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/osm/west_seattle.osm
>   file 0 extracted to "data/input/seattle/osm/west_seattle.osm"
> rm tmp_download.zip
> download https://www.dropbox.com/s/yph0zg2vqijsvb2/parcels.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/parcels.bin
>   file 0 extracted to "data/input/seattle/parcels.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/6g8rbsf200dssj3/parcels_urbansim.txt.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/parcels_urbansim.txt
>   file 0 extracted to "data/input/seattle/parcels_urbansim.txt"
> rm tmp_download.zip
> download https://www.dropbox.com/s/wdvfuw1dbqc381j/popdat.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/popdat.bin
>   file 0 extracted to "data/input/seattle/popdat.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/5ppravwmk6bf20d/trips_2014.csv.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/input/seattle/trips_2014.csv
>   file 0 extracted to "data/input/seattle/trips_2014.csv"
> rm tmp_download.zip
> download https://www.dropbox.com/s/jmgjhzwp33r5ugu/seattle.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/cities/seattle.bin
>   file 0 extracted to "data/system/cities/seattle.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/2tgd4xu7wpg5hhm/ballard.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/maps/ballard.bin
>   file 0 extracted to "data/system/maps/ballard.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/5a3br6fdzk0x79m/berlin_center.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/maps/berlin_center.bin
>   file 0 extracted to "data/system/maps/berlin_center.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/r9mobddwb0t0un5/downtown.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/maps/downtown.bin
>   file 0 extracted to "data/system/maps/downtown.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/0eml9g3bcnuxvda/huge_krakow.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/maps/huge_krakow.bin
>   file 0 extracted to "data/system/maps/huge_krakow.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/lbo4y418e2qo2it/lakeslice.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/maps/lakeslice.bin
>   file 0 extracted to "data/system/maps/lakeslice.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/f28ivdxynz2j2u5/montlake.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/maps/montlake.bin
>   file 0 extracted to "data/system/maps/montlake.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/3wzzoy9a7fnf5xg/south_seattle.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/maps/south_seattle.bin
>   file 0 extracted to "data/system/maps/south_seattle.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/8fybainsikurj79/udistrict.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/maps/udistrict.bin
>   file 0 extracted to "data/system/maps/udistrict.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/ej5zcbfr1qvpwyi/west_seattle.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/maps/west_seattle.bin
>   file 0 extracted to "data/system/maps/west_seattle.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/2ntjqw7m5f6kx4r/weekday.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/prebaked_results/lakeslice/weekday.bin
>   file 0 extracted to "data/system/prebaked_results/lakeslice/weekday.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/jefg0ikjy9dsrdd/car%20vs%20bike%20contention.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/prebaked_results/montlake/car vs bike contention.bin
>   file 0 extracted to "data/system/prebaked_results/montlake/car vs bike contention.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/1kszhaua3wsncq0/weekday.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/prebaked_results/montlake/weekday.bin
>   file 0 extracted to "data/system/prebaked_results/montlake/weekday.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/mq80nwoc9pnia5h/weekday.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/scenarios/ballard/weekday.bin
>   file 0 extracted to "data/system/scenarios/ballard/weekday.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/hkpuu0t1lpwp824/weekday.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/scenarios/downtown/weekday.bin
>   file 0 extracted to "data/system/scenarios/downtown/weekday.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/wpjbirx8ycaxvxi/weekday.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/scenarios/lakeslice/weekday.bin
>   file 0 extracted to "data/system/scenarios/lakeslice/weekday.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/b9ix4vyqtadkhhc/weekday.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/scenarios/montlake/weekday.bin
>   file 0 extracted to "data/system/scenarios/montlake/weekday.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/7cperku8ehxszfl/weekday.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/scenarios/south_seattle/weekday.bin
>   file 0 extracted to "data/system/scenarios/south_seattle/weekday.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/i4vpus5256zwn8c/weekday.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/scenarios/udistrict/weekday.bin
>   file 0 extracted to "data/system/scenarios/udistrict/weekday.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/5rgtxl9xglnyxrz/weekday.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/scenarios/west_seattle/weekday.bin
>   file 0 extracted to "data/system/scenarios/west_seattle/weekday.bin"
> rm tmp_download.zip
thread 'main' panicked at 'Failed to download stuff: ["data/input/raw_maps/lakeslice.bin failed: error getting https://www.dropbox.com/s/bcean6p6fftj4ep/lakeslice.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/bcean6p6fftj4ep/lakeslice.bin.zip)"]', updater/src/main.rs:69:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: updater::download::{{closure}}
             at updater/src/main.rs:69
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libcore/future/mod.rs:66
  10: updater::main::{{closure}}
             at updater/src/main.rs:30
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libcore/future/mod.rs:66
  12: tokio::runtime::enter::Enter::block_on::{{closure}}
             at /usr/ports/games/abstreet/work/abstreet-0.2.4-9-g10f8ddde/cargo-crates/tokio-0.2.21/src/runtime/enter.rs:163
  13: tokio::coop::with_budget::{{closure}}
             at /usr/ports/games/abstreet/work/abstreet-0.2.4-9-g10f8ddde/cargo-crates/tokio-0.2.21/src/coop.rs:127
  14: std::thread::local::LocalKey<T>::try_with
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libstd/thread/local.rs:263
  15: std::thread::local::LocalKey<T>::with
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libstd/thread/local.rs:239
  16: tokio::coop::with_budget
             at /usr/ports/games/abstreet/work/abstreet-0.2.4-9-g10f8ddde/cargo-crates/tokio-0.2.21/src/coop.rs:120
  17: tokio::coop::budget
             at /usr/ports/games/abstreet/work/abstreet-0.2.4-9-g10f8ddde/cargo-crates/tokio-0.2.21/src/coop.rs:96
  18: tokio::runtime::enter::Enter::block_on
             at /usr/ports/games/abstreet/work/abstreet-0.2.4-9-g10f8ddde/cargo-crates/tokio-0.2.21/src/runtime/enter.rs:163
  19: tokio::runtime::thread_pool::ThreadPool::block_on
             at /usr/ports/games/abstreet/work/abstreet-0.2.4-9-g10f8ddde/cargo-crates/tokio-0.2.21/src/runtime/thread_pool/mod.rs:82
  20: tokio::runtime::Runtime::block_on::{{closure}}
             at /usr/ports/games/abstreet/work/abstreet-0.2.4-9-g10f8ddde/cargo-crates/tokio-0.2.21/src/runtime/mod.rs:446
  21: tokio::runtime::context::enter
             at /usr/ports/games/abstreet/work/abstreet-0.2.4-9-g10f8ddde/cargo-crates/tokio-0.2.21/src/runtime/context.rs:72
  22: tokio::runtime::handle::Handle::enter
             at /usr/ports/games/abstreet/work/abstreet-0.2.4-9-g10f8ddde/cargo-crates/tokio-0.2.21/src/runtime/handle.rs:76
  23: tokio::runtime::Runtime::block_on
             at /usr/ports/games/abstreet/work/abstreet-0.2.4-9-g10f8ddde/cargo-crates/tokio-0.2.21/src/runtime/mod.rs:441
  24: updater::main
             at updater/src/main.rs:11
  25: std::rt::lang_start::{{closure}}
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libstd/rt.rs:67
  26: std::rt::lang_start_internal
  27: std::rt::lang_start
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libstd/rt.rs:67
  28: main
  29: _start
             at /usr/src/lib/csu/amd64/crt1.c:76
```

**Comment by dabreegster** [comment] 2020-07-20 20:09
Right, the 404 is expected. This is a dupe of #195.

**Closed by dabreegster** 2020-07-20 20:09 UTC
Labels: bug
