### ISSUE TITLE
Windows: Game crashes with GlutinCreationError(NoAvailablePixelFormat)

### ISSUE THREAD

**Issue by Costpap** [dabreegster/abstreet#79] opened 2020-06-23 13:59 UTC
Hello, I have downloaded the [latest release](https://github.com/dabreegster/abstreet/releases/tag/v0.2.0a) for Windows, but when I try to run `play_abstreet.bat`, the game will either not launch at all, or it will launch and immediately close afterwards. Below is a copy of my `output.txt` file (with `RUST_BACKTRACE` set to `full`):
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlutinCreationError(NoAvailablePixelFormat)', ezgui\src\backend_glium.rs:23:19
stack backtrace:
   0:     0x7ff6a6958a3f - <unknown>
   1:     0x7ff6a6977a9b - <unknown>
   2:     0x7ff6a695027c - <unknown>
   3:     0x7ff6a695bd4c - <unknown>
   4:     0x7ff6a695b99f - <unknown>
   5:     0x7ff6a695c527 - <unknown>
   6:     0x7ff6a695c0af - <unknown>
   7:     0x7ff6a6975710 - <unknown>
   8:     0x7ff6a6975553 - <unknown>
   9:     0x7ff6a679730b - <unknown>
  10:     0x7ff6a61f5bfb - <unknown>
  11:     0x7ff6a614cd36 - <unknown>
  12:     0x7ff6a62b0886 - <unknown>
  13:     0x7ff6a695bf47 - <unknown>
  14:     0x7ff6a6967522 - <unknown>
  15:     0x7ff6a695c878 - <unknown>
  16:     0x7ff6a614dbc7 - <unknown>
  17:     0x7ff6a69e49a4 - <unknown>
  18:     0x7ffb73336fd4 - BaseThreadInitThunk
  19:     0x7ffb7449cec1 - RtlUserThreadStart

```

**Comment by rishit-khandelwal** [comment] 2020-06-23 14:36
I have the same problem running the app.
How to resolve this issue?

**Comment by dabreegster** [comment] 2020-06-23 15:09
This is a problem in https://github.com/rust-windowing/glutin I think. I'm trying to create an OpenGL context here: https://github.com/dabreegster/abstreet/blob/27d3ec35386477c03c059516d2afc4b774881320/ezgui/src/backend_glium.rs#L20
I'm triaging a bunch of bugs, but in a few hours, I'll open up an issue with glutin and sort this out.

**Comment by dabreegster** [comment] 2020-06-23 17:23
Would somebody mind following this guide: https://github.com/rust-windowing/glutin/blob/master/ISSUES.md#debugging-on-windows

It's possible we've hit the issue with srgb mentioned at the bottom: https://github.com/rust-windowing/glutin/issues/1219. But:

```
    let context = glutin::ContextBuilder::new()
        .with_multisampling(4)
        .with_depth_buffer(2);
```
https://docs.rs/glutin/0.24.1/glutin/struct.ContextBuilder.html#method.with_srgb says the default is true

**Comment by dabreegster** [comment] 2020-06-23 19:03
Here's a dump from somebody with the issue

[glview-Intel(R) HD Graphics 4000-9.txt](https://github.com/dabreegster/abstreet/files/4821372/glview-Intel.R.HD.Graphics.4000-9.txt)

**Comment by dabreegster** [comment] 2020-06-24 16:11
Alright, I'm comparing the default settings in https://docs.rs/glutin/0.24.1/glutin/struct.PixelFormatRequirements.html with the supported pixel formats from the above dump. Formatted better is attached.
[pixel_formats.txt](https://github.com/dabreegster/abstreet/files/4826614/pixel_formats.txt)

**Comment by dabreegster** [comment] 2020-06-24 16:14
I think the problem is that I'm requesting a depth buffer with 2 bits, because that's all I need. THe default is 24. For the person who submitted their video card info, they don't have any supported configs for that low. So maybe this is the issue. I'll have a potential fix in ~20 mins, will post here

**Comment by dabreegster** [comment] 2020-06-24 16:52
Please try https://github.com/dabreegster/abstreet/suites/836769504/artifacts/9404038

**Comment by dabreegster** [comment] 2020-06-25 00:11
https://github.com/dabreegster/abstreet/releases/download/v0.2.0a/abstreet_windows_v0_2_0e.zip is the latest. One tester confirms this fix works. Could other people please give it a shot? Thanks!

**Comment by rishit-khandelwal** [comment] 2020-06-25 02:28
Is it a compiled executable? From: Dustin CarlinoSent: 24 June 2020 22:23To: dabreegster/abstreetCc: rishit-khandelwal; CommentSubject: Re: [dabreegster/abstreet] Windows: Game crashes with GlutinCreationError(NoAvailablePixelFormat) (#79) Please try https://github.com/dabreegster/abstreet/suites/836769504/artifacts/9404038—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rishit-khandelwal** [comment] 2020-06-25 02:39
It works!Thanks! From: Dustin CarlinoSent: 25 June 2020 05:42To: dabreegster/abstreetCc: rishit-khandelwal; CommentSubject: Re: [dabreegster/abstreet] Windows: Game crashes with GlutinCreationError(NoAvailablePixelFormat) (#79) https://github.com/dabreegster/abstreet/releases/download/v0.2.0a/abstreet_windows_v0_2_0e.zip is the latest. One tester confirms this fix works. Could other people please give it a shot? Thanks!—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dabreegster** [comment] 2020-06-25 03:52
I've had two people confirm this fixes this particular error, so closing the bug. Undoubtedly we will open more as we find more issues. :)  Thanks for the patience

**Closed by dabreegster** 2020-06-25 03:52 UTC
Labels: help wanted, platform specific bug
