### ISSUE TITLE
Various instances of crashing

### ISSUE THREAD

**Issue by mlincer** [dabreegster/abstreet#181] opened 2020-07-10 22:42 UTC
Output Text is below. I don't know how much it will capture. I've had a wide array of things crash the program for me. The last time it crashed, I pressed the settings icon.

load map...
Loading map ../data/system/maps/montlake.bin

Reading ../data/system/maps/montlake.bin: 0/4 MB... 0.0001s
Read ../data/system/maps/montlake.bin (4)... 0.0839s
create sim...
create sim took 0.0035s
Map and Sim cost ~0 MB
draw_map...

make DrawRoads (491)... 0.0733s
generate thick roads...
generate thick roads took 0.0049s

prepare DrawLanes (2,381)... 0.0362s

finalize DrawLanes (2,381)... 0.1961s

make DrawIntersections (371)... 0.0649s
generate unzoomed intersections...
generate unzoomed intersections took 0.0011s

make DrawBuildings (3,014)... 0.0571s
upload all buildings...
upload all buildings took 0.0361s
make DrawParkingLot...
make DrawParkingLot took 0.0054s

make DrawBusStop (16)... 0.0024s

make DrawAreas (54)... 0.0001s
upload all areas...
upload all areas took 0.0002s
create quadtree...
create quadtree took 0.1194s
static DrawMap consumes 16 MB on the GPU
draw_map... plus 0.8386s
draw_map took 1.4357s
DrawMap cost ~0 MB
load map... plus 0.0142s
load map took 1.5373s

- load map took 1.5373s
  - Read ../data/system/maps/montlake.bin (4)... 0.0839s
  - create sim took 0.0035s
  - draw_map took 1.4357s
    - make DrawRoads (491)... 0.0733s
    - generate thick roads took 0.0049s
    - prepare DrawLanes (2,381)... 0.0362s
    - finalize DrawLanes (2,381)... 0.1961s
    - make DrawIntersections (371)... 0.0649s
    - generate unzoomed intersections took 0.0011s
    - make DrawBuildings (3,014)... 0.0571s
    - upload all buildings took 0.0361s
    - make DrawParkingLot took 0.0054s
    - make DrawBusStop (16)... 0.0024s
    - make DrawAreas (54)... 0.0001s
    - upload all areas took 0.0002s
    - create quadtree took 0.1194s
    - ... plus 0.8386s
  - ... plus 0.0142s

4 notes:
Loading map ../data/system/maps/montlake.bin
Map and Sim cost ~0 MB
static DrawMap consumes 16 MB on the GPU
DrawMap cost ~0 MB

1 warnings:
Parking lane Lane #2178 has no sidewalk!

- load map took 1.5373s
Wrote ../data/player/camera_state/montlake.json

**Comment by dabreegster** [comment] 2020-07-10 22:47
Duplicate of #163 
I fixed the settings bug a few days ago; it'll be in the release this Sunday. For now, just don't click settings. :P  If you can reproduce another crash, please send the full output.txt file. This one actually got cut off and doesn't show anything useful. Github issues should let you attach .txt files.

**Comment by dabreegster** [comment] 2020-07-10 23:35
You could also try the latest build before Sunday. It should fix the settings bug (and hopefully others).

Windows: https://github.com/dabreegster/abstreet/suites/902529672/artifacts/10838033
Mac: https://github.com/dabreegster/abstreet/suites/902529672/artifacts/10838032

**Closed** 2020-07-11 23:27 UTC
