### ISSUE TITLE
Windows: misplaced mouse cursor

### ISSUE THREAD

**Issue by jholubinka** [dabreegster/abstreet#78] opened 2020-06-23 11:07 UTC
Hi, 
I'm testing the version 0_2_0c on Windows 10.

There is a slight displacement between the actual cursor position and the place where game "thinks" the cursor is. As a result, the elements of the user interface are highlighted when the mouse cursor is not directly above them. A short demonstration of the problem is here: https://imgur.com/a/ZcJKEx6 

The problem is getting more noticable in the lower part of the screen and it is related only to the vertical axis. There are no displacements in the horizontal axis.

A simple workaround I've found is to resize the game window and then make it full screen again. I suspected that it could be caused by the fact I'm using dual monitor setup (both in 1920x1080 resolution), but it doesn't to be the cause of the problem. I guess you'll need to check your initial scaling factors.

Regards,
Jakub

**Comment by bash-j** [comment] 2020-06-23 13:04
I am experiencing the same issue on my laptop with Win 10. My screen resolution is 1920x1080. The workaround fix mentioned by Jakub also solves the issue for me.

**Comment by dabreegster** [comment] 2020-06-23 15:34
Duplicate of #65

**Comment by dabreegster** [comment] 2020-06-23 15:35
Follow the other bug please. But also, where's your taskbar, the top or the bottom?

**Closed by dabreegster** 2020-06-23 15:34 UTC
